version: "3"
services:
  streamer:
    container_name: streamer
    logging:
      options:
        max-size: "50m"
    image: zipkortnicks57/foxkids_online:streamer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./series_settings/:/mnt/:ro
      - /foxkids_full/:/mnt/:ro
    networks:
      - foxkids_network

networks:
  foxkids_network:
    driver: bridge